Minion: AbstractConstraint Class Reference
AbstractConstraint Class Reference
Base type from which all constraints are derived.
#include <constraint_abstract.h>
Inherited by AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, BoolBinarySATConstraintDynamic< VarArray >, BoolLessSumConstraint< VarArray, VarSum, VarToCount >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, BoolOrConstraintDynamic< VarArray >, BoolSATConstraintDynamic< VarArray >, BoolThreeSATConstraintDynamic< VarArray >, BoundsTableConstraint< VarArray >, CheckAssignConstraint< VarArray, OriginalConstraint >, CliqueConstraint< VarArray >, ConstantConstraint< truth >, ConstantOccurrenceEqualConstraint< VarArray, Val >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, Dynamic_reify_true_old< BoolVar >, ElementConstraint< VarArray, IndexRef, VarRef >, ElementConstraintDynamic< VarArray, Index, Result >, EqualConstraint< EqualVarRef1, EqualVarRef2 >, GacAlldiff< VarArray >, GACElementConstraint< VarArray, IndexRef, VarRef >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GadgetConstraint< VarArray >, GCC< VarArray1, VarArray2, Strongcards >, GraphIsoConstraint< VarArray >, LeqConstraint< VarRef1, VarRef2, Offset >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, LexLeqConstraint< VarArray1, VarArray2, Less >, LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, MinConstraint< VarArray, MinVarRef >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NeqConstraintBinary< VarRef1, VarRef2 >, NewTableConstraint< VarArray, TableDataType, TableStateType >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, OccurrenceEqualConstraint< VarArray, Val, ValCount >, ParentConstraint, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, ReifiedEqualConstraint< EqualVarRef1, EqualVarRef2, BoolVarRef >, reify_true_old< BoolVar >, SumEqConstraintDynamic< VarRef1, VarRef2, VarRef3 >, TableConstraint< VarArray >, UnaryEqualConstraint< VarRef, Offset >, UnaryNeqConstraint< VarRef, Offset >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLessConstraint< Var1, Var2, Negated >, WatchLiteralConstraint< Var >, WatchNeqConstraint< Var1, Var2 >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, WatchNotLiteralBoolConstraint, and WatchNotLiteralConstraint< Var >.
Public Member Functions
DynamicTrigger * dynamic_trigger_start ()
Returns a point to the first dynamic trigger of the constraint.
virtual int dynamic_trigger_count ()
virtual int dynamic_trigger_count_with_children ()
virtual triggerCollection setup_internal ()
Gets all the triggers a constraint wants to set up.
virtual void propagate (DynamicTrigger *)
Iterative propagation function.
virtual void propagate (int, DomainDelta)
Iterative propagation function.
virtual BOOL full_check_unsat ()
virtual BOOL check_unsat (int, DomainDelta)
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
AbstractConstraint (StateObj *_stateObj)
virtual string constraint_name ()=0
Method to get constraint name for debugging.
virtual void full_propagate ()=0
Performs a full round of propagation and sets up any data needs by propagate().
virtual vector< AnyVarRef > get_vars ()=0
vector< AnyVarRef > * get_vars_singleton ()
virtual int getTrigWeight ()
virtual void special_check ()
virtual void special_unlock ()
virtual BOOL check_assignment (DomainInt *v, int v_size)=0
Checks if an assignment is satisfied.
virtual void setup_dynamic_triggers (MemOffset DynamicTriggerPointer)
virtual triggerCollection setup_internal_gather_triggers ()
virtual void setup ()
Public Attributes
BOOL full_propagate_done
Protected Attributes
StateObj * stateObj
Private members of the base class.
MemOffset _DynamicTriggerCache
vector< AnyVarRef > singleton_vars
Detailed Description
Base type from which all constraints are derived.
Definition at line 56 of file constraint_abstract.h.
Member Function Documentation
virtual int AbstractConstraint::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented in GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, BoolBinarySATConstraintDynamic< VarArray >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLiteralConstraint< Var >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, and WatchNotLiteralConstraint< Var >.
Definition at line 80 of file constraint_abstract.h.
Referenced by ParentConstraint::dynamic_trigger_count_with_children(), dynamic_trigger_count_with_children(), ParentConstraint::setup(), and setup().
virtual int AbstractConstraint::dynamic_trigger_count_with_children () [inline, virtual]
Returns the number of dynamic triggers for this constraint, and all the children of this constraint. Only differs from the above for things like 'reify', 'reifyimply' and 'or'.
Reimplemented in ParentConstraint.
Definition at line 85 of file constraint_abstract.h.
References dynamic_trigger_count().
virtual triggerCollection AbstractConstraint::setup_internal () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, ConstantConstraint< truth >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, ReifiedEqualConstraint< EqualVarRef1, EqualVarRef2, BoolVarRef >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, and LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >.
Definition at line 90 of file constraint_abstract.h.
Referenced by ParentConstraint::setup_internal_gather_triggers().
virtual void AbstractConstraint::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented in GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, BoolBinarySATConstraintDynamic< VarArray >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLiteralConstraint< Var >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, and WatchNotLiteralConstraint< Var >.
Definition at line 95 of file constraint_abstract.h.
References constraint_name().
Referenced by DynamicTrigger::propagate().
virtual void AbstractConstraint::propagate (int , DomainDelta) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, ConstantConstraint< truth >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, ReifiedEqualConstraint< EqualVarRef1, EqualVarRef2, BoolVarRef >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, and LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >.
Definition at line 100 of file constraint_abstract.h.
References constraint_name().
virtual BOOL AbstractConstraint::full_check_unsat () [inline, virtual]
Checks if a constraint cannot be satisfied, and sets up any data structures for future incremental checks. Returns TRUE if constraint cannot be satisfied. This function is used by rarification
Reimplemented in LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, NeqConstraint< VarArray >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, and LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >.
Definition at line 106 of file constraint_abstract.h.
References constraint_name().
virtual BOOL AbstractConstraint::check_unsat (int , DomainDelta) [inline, virtual]
Checks incrementaly if constraint cannot be satisfied. Returns TRUE if constraint cannot be satisfied. This function should not be called unless check_unsat_full is called first. This is used by rarification
Reimplemented in LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, NeqConstraint< VarArray >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, and LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >.
Definition at line 115 of file constraint_abstract.h.
References constraint_name().
virtual bool AbstractConstraint::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, ConstantConstraint< truth >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >, BoolBinarySATConstraintDynamic< VarArray >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLiteralConstraint< Var >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, and WatchNotLiteralConstraint< Var >.
Definition at line 125 of file constraint_abstract.h.
References constraint_name().
virtual AbstractConstraint* AbstractConstraint::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, and VecNeqDynamic< VarArray1, VarArray2, Operator >.
Definition at line 133 of file constraint_abstract.h.
References constraint_name().
virtual void AbstractConstraint::full_propagate () [pure virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, ConstantConstraint< truth >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, ReifiedEqualConstraint< EqualVarRef1, EqualVarRef2, BoolVarRef >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >, BoolBinarySATConstraintDynamic< VarArray >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLiteralConstraint< Var >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, and WatchNotLiteralConstraint< Var >.
virtual void AbstractConstraint::special_check () [inline, virtual]
Allows functions to activate a special kind of trigger, run only after the normal queue is empty.
Definition at line 177 of file constraint_abstract.h.
virtual BOOL AbstractConstraint::check_assignment (DomainInt * v, int v_size) [pure virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implemented in AbsConstraint< AbsVarRef1, AbsVarRef2 >, AndConstraint< VarRef1, VarRef2, VarRef3 >, ConstantConstraint< truth >, DifferenceConstraint< VarRef1, VarRef2, VarRef3 >, DivConstraint< VarRef1, VarRef2, VarRef3 >, ElementConstraint< VarArray, IndexRef, VarRef >, ReifiedEqualConstraint< EqualVarRef1, EqualVarRef2, BoolVarRef >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, GACTableConstraint< VarArray >, LeqConstraint< VarRef1, VarRef2, Offset >, LexLeqConstraint< VarArray1, VarArray2, Less >, MinConstraint< VarArray, MinVarRef >, NotModConstraint< VarRef1, VarRef2, VarRef3 >, ModConstraint< VarRef1, VarRef2, VarRef3 >, NeqConstraint< VarArray >, NotOccurrenceEqualConstraint< VarArray, Val, ValCount >, PowConstraint< VarRef1, VarRef2, VarRef3 >, ProductConstraint< VarRef1, VarRef2, VarRef3 >, LessEqualSumConstraint< VarArray, VarSum, is_reversed >, LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >, BoolBinarySATConstraintDynamic< VarArray >, ElementConstraintDynamic< VarArray, Index, Result >, WatchLessConstraint< Var1, Var2, Negated >, LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >, BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >, VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >, VecNeqDynamic< VarArray1, VarArray2, Operator >, WatchInRangeConstraint< Var >, WatchInSetConstraint< Var >, WatchLiteralConstraint< Var >, WatchNotInRangeConstraint< Var >, WatchNotInSetConstraint< Var >, and WatchNotLiteralConstraint< Var >.
virtual void AbstractConstraint::setup () [inline, virtual]
Actually creates the dynamic triggers. Calls dynamic_trigger_count from function to get the number of triggers required.
Reimplemented in ParentConstraint.
Definition at line 208 of file constraint_abstract.h.
References dynamic_trigger_count(), dynamic_trigger_start(), and stateObj.
The documentation for this class was generated from the following file:
constraint_abstract.h