Minion: MoveablePointer Class Reference
MoveablePointer Class Reference
[Memory]
Class which represents a moveable pointer.
#include <MemoryBlock.h>
Public Member Functions
MoveablePointer (const MoveablePointer &b)
Copy constructor for MoveablePointer.
void operator= (const MoveablePointer &b)
Assignment for MoveablePointer.
MoveablePointer (void *ptr)
Constructs a MoveablePointer from a raw pointer ptr.
MoveablePointer (const MoveablePointer &mp, int offset)
Constructs a MoveablePointer from a MoveablePointer and an offset in bytes.
void * get_ptr_noCheck () const
In debug mode, gets the pointer without checking if it is valid.
void * get_ptr () const
Returns the pointer.
bool is_null () const
void set_raw_ptr (void *_ptr)
MoveablePointer getOffset (unsigned bytes)
Produces a new MoveablePointer offset from the current one by a given number of bytes.
MoveablePointer ()
Default constructor.
~MoveablePointer ()
Destructor.
Private Attributes
void * ptr
The physical pointer being wrapped.
Detailed Description
Class which represents a moveable pointer.
This class represents any point in Minion which should be moveable. The two main sources of these are both backtrackable and nonbacktrackable memory. There are always design tradeoffs with this kind of pointer. In this case the choice made has been to make storing and dereferencing the pointer as cheap as possible, while making copying the pointer quite expensive.
Note that while this returns a raw pointer, it is important to not keep that pointer across any function call which could either allocate new memory or push or pop the search state stack.
Definition at line 46 of file MemoryBlock.h.
Member Function Documentation
void* MoveablePointer::get_ptr_noCheck () const [inline]
In debug mode, gets the pointer without checking if it is valid.
This can be used in non-debug mode, but does not do anything. It is used by the code which does checking of get_ptr in debug mode.
Definition at line 67 of file MemoryBlock.h.
References ptr.
Referenced by NewMemoryBlock::checkAddToTracker(), NewMemoryBlock::checkPointerValid(), and NewMemoryBlock::checkRemoveFromTracker().
void MoveablePointer::set_raw_ptr (void * _ptr) [inline]
Manually alters the pointer being watched. This function should only be used by those with a complete understanding of the whole memory system, and in special circumstances.
Definition at line 84 of file MemoryBlock.h.
References ptr.
The documentation for this class was generated from the following file:
MemoryBlock.h