Minion: ParentConstraint Class Reference
ParentConstraint Class Reference
Constraint from which other constraints can be inherited. Extends dynamicconstraint to allow children to be dynamic.
#include <constraint_abstract.h>
Public Member Functions
pair< int, int > getChildStaticTrigger (int i)
int getChildDynamicTrigger (DynamicTrigger *ptr)
virtual triggerCollection setup_internal_gather_triggers ()
Gets all the triggers a constraint wants to set up.
ParentConstraint (StateObj *_stateObj, const vector< AbstractConstraint * > _children=vector< AbstractConstraint * >())
virtual int dynamic_trigger_count_with_children ()
virtual void setup_dynamic_triggers (MemOffset dynamicTriggerPointer)
virtual void setup ()
Protected Attributes
vector< AbstractConstraint * > child_constraints
vector< int > _dynamic_trigger_to_constraint
vector< pair< int, int > > _static_trigger_to_constraint
vector< int > variable_to_constraint
vector< int > start_of_constraint
Detailed Description
Constraint from which other constraints can be inherited. Extends dynamicconstraint to allow children to be dynamic.
Definition at line 229 of file constraint_abstract.h.
Member Function Documentation
virtual triggerCollection ParentConstraint::setup_internal_gather_triggers () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented from AbstractConstraint.
Definition at line 253 of file constraint_abstract.h.
References AbstractConstraint::setup_internal().
Referenced by setup().
virtual int ParentConstraint::dynamic_trigger_count_with_children () [inline, virtual]
Returns the number of dynamic triggers for this constraint, and all the children of this constraint. Only differs from the above for things like 'reify', 'reifyimply' and 'or'.
Reimplemented from AbstractConstraint.
Definition at line 295 of file constraint_abstract.h.
References AbstractConstraint::dynamic_trigger_count().
Referenced by setup().
virtual void ParentConstraint::setup () [inline, virtual]
Actually creates the dynamic triggers. Calls dynamic_trigger_count from function to get the number of triggers required.
Reimplemented from AbstractConstraint.
Definition at line 334 of file constraint_abstract.h.
References AbstractConstraint::dynamic_trigger_count(), dynamic_trigger_count_with_children(), MoveablePointer::get_ptr(), Memory::nonBackTrack(), NewMemoryBlock::request_bytes(), setup_internal_gather_triggers(), and AbstractConstraint::stateObj.
The documentation for this class was generated from the following file:
constraint_abstract.h