Minion: LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum > Struct Template Reference
LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum > Struct Template Reference
#include <dynamic_literalwatch.h>
Public Types
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
int & unwatched (int i)
LiteralSumConstraintDynamic (StateObj *_stateObj, const VarArray &_var_array, ValueArray _val_array, VarSum _var_sum)
int dynamic_trigger_count ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
BOOL check_consistency ()
Checks the consistency of the constraint's data structures.
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
Public Attributes
VarArray var_array
ValueArray value_array
MemOffset unwatched_indexes
int last
int num_unwatched
VarSum var_sum
Detailed Description
template<typename VarArray, typename ValueArray, typename VarSum>
struct LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >
constraints;litsumgeq Description The constraint litsumgeq(vec1, vec2, c) ensures that there exists at least c distinct indices i such that vec1[i] = vec2[i]. constraints;litsumgeq Notes A SAT clause {x,y,z} can be created using:
litsumgeq([x,y,z],[1,1,1],1)
Note also that this constraint is more efficient for smaller values of c. For large values consider using watchsumleq. constraints;litsumgeq Reifiability This constraint is not reifiable. constraints;litsumgeq References See also
help constraints watchsumleq help constraints watchsumgeq
Definition at line 49 of file dynamic_literalwatch.h.
Member Function Documentation
template<typename VarArray, typename ValueArray, typename VarSum> int LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 82 of file dynamic_literalwatch.h.
template<typename VarArray, typename ValueArray, typename VarSum> virtual void LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 91 of file dynamic_literalwatch.h.
References AbstractConstraint::dynamic_trigger_start(), AbstractConstraint::stateObj, and DynamicTrigger::trigger_info().
template<typename VarArray, typename ValueArray, typename VarSum> virtual void LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 173 of file dynamic_literalwatch.h.
References LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::check_consistency(), AbstractConstraint::dynamic_trigger_start(), and DynamicTrigger::trigger_info().
template<typename VarArray, typename ValueArray, typename VarSum> virtual BOOL LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 230 of file dynamic_literalwatch.h.
template<typename VarArray, typename ValueArray, typename VarSum> virtual bool LiteralSumConstraintDynamic< VarArray, ValueArray, VarSum >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 248 of file dynamic_literalwatch.h.
The documentation for this struct was generated from the following file:
dynamic_literalwatch.h