Minion: BoolBinarySATConstraintDynamic< VarArray > Struct Template Reference
BoolBinarySATConstraintDynamic< VarArray > Struct Template Reference
Specialised SAT implementation for just 2 variables.
#include <dynamic_binary_sat.h>
Public Types
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
BoolBinarySATConstraintDynamic (StateObj *_stateObj, const VarArray &_var_array)
int dynamic_trigger_count ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
Public Attributes
VarRef var1
VarRef var2
Detailed Description
template<typename VarArray>
struct BoolBinarySATConstraintDynamic< VarArray >
Specialised SAT implementation for just 2 variables.
Definition at line 25 of file dynamic_binary_sat.h.
Member Function Documentation
template<typename VarArray> int BoolBinarySATConstraintDynamic< VarArray >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 39 of file dynamic_binary_sat.h.
template<typename VarArray> virtual void BoolBinarySATConstraintDynamic< VarArray >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 44 of file dynamic_binary_sat.h.
References AbstractConstraint::dynamic_trigger_start(), and DynamicTrigger::trigger_info().
template<typename VarArray> virtual void BoolBinarySATConstraintDynamic< VarArray >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 71 of file dynamic_binary_sat.h.
References DynamicTrigger::trigger_info().
template<typename VarArray> virtual BOOL BoolBinarySATConstraintDynamic< VarArray >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 82 of file dynamic_binary_sat.h.
template<typename VarArray> virtual bool BoolBinarySATConstraintDynamic< VarArray >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 96 of file dynamic_binary_sat.h.
The documentation for this struct was generated from the following file:
dynamic_binary_sat.h