Minion: NotOccurrenceEqualConstraint< VarArray, Val, ValCount > Struct Template Reference
NotOccurrenceEqualConstraint< VarArray, Val, ValCount > Struct Template Reference
#include <constraint_occurrence.h>
Public Types
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
NotOccurrenceEqualConstraint (StateObj *_stateObj, const VarArray &_var_array, const Val &_value, const ValCount &_val_count)
int dynamic_trigger_count ()
virtual triggerCollection setup_internal ()
Gets all the triggers a constraint wants to set up.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual void propagate (int z, DomainDelta)
Iterative propagation function.
virtual void propagate (DynamicTrigger *trig)
Iterative propagation function.
int watch_unassigned_in_vector (int avoidindex, int oldsupport, DynamicTrigger *dt)
void vector_assigned ()
void valcount_assigned ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
Public Attributes
ReversibleInt occurrences_count
ReversibleInt not_occurrences_count
VarArray var_array
ValCount val_count
Val value
int trigger1index
int trigger2index
Detailed Description
template<typename VarArray, typename Val, typename ValCount>
struct NotOccurrenceEqualConstraint< VarArray, Val, ValCount >
constraints;occurrence Description The constraint
occurrence(vec, elem, count)
ensures that there are count occurrences of the value elem in the vector vec. constraints;occurrence Notes elem must be a constant, not a variable. constraints;occurrence References help constraints occurrenceleq help constraints occurrencegeq constraints;occurrenceleq Description The constraint
occurrenceleq(vec, elem, count)
ensures that there are AT MOST count occurrences of the value elem in the vector vec. constraints;occurrenceleq Notes elem and count must be constants constraints;occurrenceleq References help constraints occurrence help constraints occurrencegeq constraints;occurrencegeq Description The constraint
occurrencegeq(vec, elem, count)
ensures that there are AT LEAST count occurrences of the value elem in the vector vec. constraints;occurrencegeq Notes elem and count must be constants constraints;occurrencegeq References help constraints occurrence help constraints occurrenceleq
Definition at line 79 of file constraint_occurrence.h.
Member Function Documentation
template<typename VarArray, typename Val, typename ValCount> int NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 105 of file constraint_occurrence.h.
template<typename VarArray, typename Val, typename ValCount> virtual triggerCollection NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::setup_internal () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented from AbstractConstraint.
Definition at line 110 of file constraint_occurrence.h.
template<typename VarArray, typename Val, typename ValCount> virtual BOOL NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 117 of file constraint_occurrence.h.
Referenced by NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::get_satisfying_assignment().
template<typename VarArray, typename Val, typename ValCount> virtual void NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::propagate (int , DomainDelta) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 137 of file constraint_occurrence.h.
References AbstractConstraint::dynamic_trigger_start().
template<typename VarArray, typename Val, typename ValCount> virtual void NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 162 of file constraint_occurrence.h.
References AbstractConstraint::dynamic_trigger_start(), and AbstractConstraint::stateObj.
template<typename VarArray, typename Val, typename ValCount> virtual void NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 313 of file constraint_occurrence.h.
References AbstractConstraint::dynamic_trigger_start().
template<typename VarArray, typename Val, typename ValCount> virtual bool NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 337 of file constraint_occurrence.h.
References NotOccurrenceEqualConstraint< VarArray, Val, ValCount >::check_assignment().
The documentation for this struct was generated from the following file:
constraint_occurrence.h