Minion: VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed > Struct Template Reference
VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed > Struct Template Reference
#include <dynamic_sumor.h>
Public Types
typedef VarArray1::value_type VarRef1
typedef VarArray2::value_type VarRef2
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
VecCountDynamic (StateObj *_stateObj, const VarArray1 &_array1, const VarArray2 &_array2, int _hamming_distance)
int dynamic_trigger_count ()
bool no_support_for_index (int index)
void add_triggers (int index, DynamicTrigger *dt)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
void initalise_unwatched_values ()
void propagate_from_var1 (int index)
void propagate_from_var2 (int index)
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
template<bool b>
disable_if_c< b,
AbstractConstraint * >::type rev_implement ()
template<bool b>
enable_if_c< b,
AbstractConstraint * >::type rev_implement ()
Public Attributes
VarArray1 var_array1
VarArray2 var_array2
int num_to_watch
int hamming_distance
vector< int > watched_values
vector< int > unwatched_values
Reversible< bool > propagate_mode
int index_to_not_propagate
Detailed Description
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false>
struct VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >
constraints;hamming Description The constraint
hamming(X,Y,c)
ensures that the hamming distance between X and Y is at least c. That is, that the size of the set {i | X[i] != y[i]} is greater than or equal to c.
Definition at line 43 of file dynamic_sumor.h.
Member Function Documentation
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> int VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 70 of file dynamic_sumor.h.
Referenced by VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::propagate().
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> virtual void VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 82 of file dynamic_sumor.h.
References AbstractConstraint::dynamic_trigger_start(), and AbstractConstraint::stateObj.
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> virtual void VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 166 of file dynamic_sumor.h.
References VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::dynamic_trigger_count(), and AbstractConstraint::dynamic_trigger_start().
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> virtual BOOL VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 243 of file dynamic_sumor.h.
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> virtual bool VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 264 of file dynamic_sumor.h.
template<typename VarArray1, typename VarArray2, typename Operator = NeqIterated, BOOL is_reversed = false> virtual AbstractConstraint* VecCountDynamic< VarArray1, VarArray2, Operator, is_reversed >::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented from AbstractConstraint.
Definition at line 289 of file dynamic_sumor.h.
The documentation for this struct was generated from the following file:
dynamic_sumor.h