Minion: LessEqualSumConstraint< VarArray, VarSum, is_reversed > Struct Template Reference
LessEqualSumConstraint< VarArray, VarSum, is_reversed > Struct Template Reference
#include <constraint_fullsum.h>
Public Types
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
LessEqualSumConstraint (StateObj *_stateObj, const VarArray &_var_array, VarSum _var_sum)
virtual triggerCollection setup_internal ()
Gets all the triggers a constraint wants to set up.
DomainInt get_real_min_sum ()
DomainInt get_real_max_diff ()
virtual void propagate (int prop_val, DomainDelta domain_change)
Iterative propagation function.
virtual BOOL check_unsat (int prop_val, DomainDelta domain_change)
virtual BOOL full_check_unsat ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual vector< AnyVarRef > get_vars ()
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
template<bool b>
disable_if_c< b,
AbstractConstraint * >::type rev_implement ()
template<bool b>
enable_if_c< b,
AbstractConstraint * >::type rev_implement ()
Public Attributes
bool no_negatives
VarArray var_array
VarSum var_sum
Reversible< DomainInt > max_looseness
Reversible< DomainInt > var_array_min_sum
Detailed Description
template<typename VarArray, typename VarSum, BOOL is_reversed = false>
struct LessEqualSumConstraint< VarArray, VarSum, is_reversed >
V1 + ... Vn <= X is_reversed checks if we are in the case where reverse_constraint was previously called.
Definition at line 52 of file constraint_fullsum.h.
Member Function Documentation
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual triggerCollection LessEqualSumConstraint< VarArray, VarSum, is_reversed >::setup_internal () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented from AbstractConstraint.
Definition at line 81 of file constraint_fullsum.h.
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual void LessEqualSumConstraint< VarArray, VarSum, is_reversed >::propagate (int , DomainDelta) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 110 of file constraint_fullsum.h.
References AbstractConstraint::stateObj.
Referenced by LessEqualSumConstraint< VarArray, VarSum, is_reversed >::full_propagate().
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual BOOL LessEqualSumConstraint< VarArray, VarSum, is_reversed >::check_unsat (int , DomainDelta) [inline, virtual]
Checks incrementaly if constraint cannot be satisfied. Returns TRUE if constraint cannot be satisfied. This function should not be called unless check_unsat_full is called first. This is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 142 of file constraint_fullsum.h.
Referenced by LessEqualSumConstraint< VarArray, VarSum, is_reversed >::full_check_unsat().
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual BOOL LessEqualSumConstraint< VarArray, VarSum, is_reversed >::full_check_unsat () [inline, virtual]
Checks if a constraint cannot be satisfied, and sets up any data structures for future incremental checks. Returns TRUE if constraint cannot be satisfied. This function is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 153 of file constraint_fullsum.h.
References LessEqualSumConstraint< VarArray, VarSum, is_reversed >::check_unsat().
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual void LessEqualSumConstraint< VarArray, VarSum, is_reversed >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 169 of file constraint_fullsum.h.
References LessEqualSumConstraint< VarArray, VarSum, is_reversed >::propagate().
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual BOOL LessEqualSumConstraint< VarArray, VarSum, is_reversed >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 188 of file constraint_fullsum.h.
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual bool LessEqualSumConstraint< VarArray, VarSum, is_reversed >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 197 of file constraint_fullsum.h.
template<typename VarArray, typename VarSum, BOOL is_reversed = false> virtual AbstractConstraint* LessEqualSumConstraint< VarArray, VarSum, is_reversed >::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented from AbstractConstraint.
Definition at line 242 of file constraint_fullsum.h.
The documentation for this struct was generated from the following file:
constraint_fullsum.h