Minion: WatchNotInSetConstraint< Var > Struct Template Reference
WatchNotInSetConstraint< Var > Struct Template Reference
#include <dynamic_notinset.h>
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
template<typename T >
WatchNotInSetConstraint (StateObj *_stateObj, const Var &_var, const T &_vals)
int dynamic_trigger_count ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
Public Attributes
Var var
vector< DomainInt > vals
Detailed Description
template<typename Var>
struct WatchNotInSetConstraint< Var >
constraints;w-notinset Description The constraint w-notinset(x, [a1,...,an]) ensures that x does not belong to the set {a1,..,an}. constraints;w-notinset References See also
help constraints w-inset
Definition at line 36 of file dynamic_notinset.h.
Member Function Documentation
template<typename Var> int WatchNotInSetConstraint< Var >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 50 of file dynamic_notinset.h.
template<typename Var> virtual void WatchNotInSetConstraint< Var >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 53 of file dynamic_notinset.h.
References AbstractConstraint::dynamic_trigger_start(), and WatchNotInSetConstraint< Var >::propagate().
template<typename Var> virtual void WatchNotInSetConstraint< Var >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 70 of file dynamic_notinset.h.
Referenced by WatchNotInSetConstraint< Var >::full_propagate().
template<typename Var> virtual BOOL WatchNotInSetConstraint< Var >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 93 of file dynamic_notinset.h.
template<typename Var> virtual bool WatchNotInSetConstraint< Var >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
TODO: Make faster
Reimplemented from AbstractConstraint.
Definition at line 107 of file dynamic_notinset.h.
The documentation for this struct was generated from the following file:
dynamic_notinset.h