Minion: WatchNotInRangeConstraint< Var > Struct Template Reference
WatchNotInRangeConstraint< Var > Struct Template Reference
#include <dynamic_notinrange.h>
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
template<typename T >
WatchNotInRangeConstraint (StateObj *_stateObj, const Var &_var, const T &_vals)
int dynamic_trigger_count ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
Public Attributes
Var var
DomainInt range_min
DomainInt range_max
Detailed Description
template<typename Var>
struct WatchNotInRangeConstraint< Var >
constraints;w-notinrange Description The constraint w-notinrange(x, [a,b]) ensures that x < a or b < x. constraints;w-notinrange References See also
help constraints w-inrange
Definition at line 35 of file dynamic_notinrange.h.
Member Function Documentation
template<typename Var> int WatchNotInRangeConstraint< Var >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 59 of file dynamic_notinrange.h.
template<typename Var> virtual void WatchNotInRangeConstraint< Var >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 62 of file dynamic_notinrange.h.
References AbstractConstraint::dynamic_trigger_start(), and WatchNotInRangeConstraint< Var >::propagate().
template<typename Var> virtual void WatchNotInRangeConstraint< Var >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 94 of file dynamic_notinrange.h.
Referenced by WatchNotInRangeConstraint< Var >::full_propagate().
template<typename Var> virtual BOOL WatchNotInRangeConstraint< Var >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 112 of file dynamic_notinrange.h.
template<typename Var> virtual bool WatchNotInRangeConstraint< Var >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
TODO: Make faster
Reimplemented from AbstractConstraint.
Definition at line 126 of file dynamic_notinrange.h.
The documentation for this struct was generated from the following file:
dynamic_notinrange.h