Minion: GACTableConstraint< VarArray > Struct Template Reference
GACTableConstraint< VarArray > Struct Template Reference
#include <constraint_GACtable.h>
Public Types
typedef VarArray::value_type VarRef
typedef VarArray::value_type VarRef
typedef VarArray::value_type VarRef
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
int * current_support ()
vector< int > & supporting_tuple (int i)
Returns the tuple currently supporting a given literal.
bool check_tuple (const vector< int > &v)
Check if all allowed values in a given tuple are still in the domains of the variables.
GACTableConstraint (const VarArray &_vars, TupleList *_tuples)
int dynamic_trigger_count ()
bool find_new_support (int literal, int var)
virtual void propagate (DynamicTrigger *propagated_trig)
Iterative propagation function.
void setup_watches (int var, int val)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual string constraint_name ()
Method to get constraint name for debugging.
bool check_tuple (const vector< int > &v)
Check if all allowed values in a given tuple are still in the domains of the variables.
bool check_tuple (int *v)
int comparetuples (int *t1, int *t2)
GACTableConstraint (const VarArray &_vars, TupleList *tuples)
int dynamic_trigger_count ()
TupleN * seekNextSupport (int var, int val)
bool find_new_support (int literal)
virtual void propagate (DynamicTrigger *propagated_trig)
Iterative propagation function.
void setup_watches (int var, int val, int lit)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual string constraint_name ()
Method to get constraint name for debugging.
BOOL check_tuple (const vector< int > &v)
Check if all allowed values in a given tuple are still in the domains of the variables.
BOOL check_tuple (int *v)
int comparetuples (int *t1, int *t2)
GACTableConstraint (const VarArray &_vars, TupleList *_tuples)
int dynamic_trigger_count ()
TupleH * seekNextSupport (int var, int val)
int nextin (int var, int val, int curtuple)
bool find_new_support (int literal)
virtual void propagate (DynamicTrigger *propagated_trig)
Iterative propagation function.
void setup_watches (int var, int val, int lit)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual string constraint_name ()
Method to get constraint name for debugging.
BOOL check_tuple (const vector< int > &v)
Check if all allowed values in a given tuple are still in the domains of the variables.
GACTableConstraint (StateObj *_stateObj, const VarArray &_vars, TupleList *_tuples)
int dynamic_trigger_count ()
BOOL find_new_support (int literal)
virtual void propagate (DynamicTrigger *propagated_trig)
Iterative propagation function.
void setup_watches (int var, int lit)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
Public Attributes
VarArray vars
LiteralSpecificLists * lists
MemOffset _current_support
int ** current_support
For each literal, the number of the tuple that supports it.
int arity
Nightingale * nightingale
ReversibleInt *** current_support
For each literal, the number of the tuple that supports it.
vector< int > offset
TupleList * tupleList
BOOL listdone
int noTuples
int * upperboundtuple
Regin * regin
TupleTrieArray * tupleTrieArrayptr
DomainInt * recyclableTuple
vector< TrieObj ** > trie_current_support
For each literal, the number of the tuple that supports it.
TupleList * tuples
Detailed Description
template<typename VarArray>
struct GACTableConstraint< VarArray >
constraints;table Description An extensional constraint that enforces GAC. The constraint is specified via a list of tuples. constraints;table Example To specify a constraint over 3 variables that allows assignments (0,0,0), (1,0,0), (0,1,0) or (0,0,1) do the following.
1) Add a tuplelist to the **TUPLELIST** section, e.g.:
TUPLELIST** myext 4 3 0 0 0 1 0 0 0 1 0 0 0 1
N.B. the number 4 is the number of tuples in the constraint, the number 3 is the -arity.
2) Add a table constraint to the **CONSTRAINTS** section, e.g.:
CONSTRAINTS** table(myvec, myext)
and now the variables of myvec will satisfy the constraint myext. constraints;table Example The constraints extension can also be specified in the constraint definition, e.g.:
table(myvec, {<0,0,0>,<1,0,0>,<0,1,0>,<0,0,1>}) constraints;table References help input tuplelist help input negativetable constraints;negativetable Description An extensional constraint that enforces GAC. The constraint is specified via a list of disallowed tuples. constraints;negativetable Notes See entry
help input negativetable
for how to specify a table constraint in minion input. The only difference for negativetable is that the specified tuples are disallowed. constraints;negativetable References help input table help input tuplelist
Definition at line 85 of file constraint_GACtable.h.
Member Function Documentation
template<typename VarArray> int GACTableConstraint< VarArray >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 170 of file constraint_GACtable.h.
References LiteralSpecificLists::tuples.
template<typename VarArray> virtual void GACTableConstraint< VarArray >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 230 of file constraint_GACtable.h.
References AbstractConstraint::dynamic_trigger_start(), and LiteralSpecificLists::tuples.
template<typename VarArray> virtual void GACTableConstraint< VarArray >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 271 of file constraint_GACtable.h.
References GACTableConstraint< VarArray >::current_support, LiteralSpecificLists::literal_specific_tuples, AbstractConstraint::stateObj, and LiteralSpecificLists::tuples.
template<typename VarArray> virtual BOOL GACTableConstraint< VarArray >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 305 of file constraint_GACtable.h.
References LiteralSpecificLists::tuples.
template<typename VarArray> int GACTableConstraint< VarArray >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 299 of file constraint_GACtable_nightingale.h.
template<typename VarArray> virtual void GACTableConstraint< VarArray >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 413 of file constraint_GACtable_nightingale.h.
References AbstractConstraint::dynamic_trigger_start().
template<typename VarArray> virtual void GACTableConstraint< VarArray >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 460 of file constraint_GACtable_nightingale.h.
References AbstractConstraint::stateObj.
template<typename VarArray> virtual BOOL GACTableConstraint< VarArray >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 497 of file constraint_GACtable_nightingale.h.
template<typename VarArray> int GACTableConstraint< VarArray >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 267 of file constraint_GACtable_reginlhomme.h.
template<typename VarArray> virtual void GACTableConstraint< VarArray >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 403 of file constraint_GACtable_reginlhomme.h.
References AbstractConstraint::dynamic_trigger_start().
template<typename VarArray> virtual void GACTableConstraint< VarArray >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 446 of file constraint_GACtable_reginlhomme.h.
References GACTableConstraint< VarArray >::current_support, and AbstractConstraint::stateObj.
template<typename VarArray> virtual BOOL GACTableConstraint< VarArray >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 479 of file constraint_GACtable_reginlhomme.h.
template<typename VarArray> int GACTableConstraint< VarArray >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 81 of file constraint_GACtable_trie.h.
template<typename VarArray> virtual void GACTableConstraint< VarArray >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 114 of file constraint_GACtable_trie.h.
References AbstractConstraint::dynamic_trigger_start().
template<typename VarArray> virtual void GACTableConstraint< VarArray >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 164 of file constraint_GACtable_trie.h.
References AbstractConstraint::stateObj, and GACTableConstraint< VarArray >::trie_current_support.
template<typename VarArray> virtual BOOL GACTableConstraint< VarArray >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 227 of file constraint_GACtable_trie.h.
The documentation for this struct was generated from the following files:
constraint_GACtable.h
constraint_GACtable_nightingale.h
constraint_GACtable_reginlhomme.h
constraint_GACtable_trie.h