Minion: LexLeqConstraint< VarArray1, VarArray2, Less > Struct Template Reference
LexLeqConstraint< VarArray1, VarArray2, Less > Struct Template Reference
#include <constraint_lex.h>
Public Types
typedef LexLeqConstraint
< VarArray2, VarArray1,!Less > NegConstraintType
typedef VarArray1::value_type ArrayVarRef1
typedef VarArray2::value_type ArrayVarRef2
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
LexLeqConstraint (StateObj *_stateObj, const VarArray1 &_x, const VarArray2 &_y)
virtual triggerCollection setup_internal ()
Gets all the triggers a constraint wants to set up.
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
void updateAlpha (int i)
void updateBeta (int i)
virtual void propagate (int i, DomainDelta)
Iterative propagation function.
virtual BOOL check_unsat (int unsat_val, DomainDelta)
virtual BOOL full_check_unsat ()
BOOL checkLex (int i)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual vector< AnyVarRef > get_vars ()
Public Attributes
ReversibleInt alpha
ReversibleInt beta
ReversibleInt F
VarArray1 x
VarArray2 y
Detailed Description
template<typename VarArray1, typename VarArray2, BOOL Less = false>
struct LexLeqConstraint< VarArray1, VarArray2, Less >
constraints;lexless Description The constraint
lexless(vec0, vec1)
takes two vectors vec0 and vec1 of the same length and ensures that vec0 is lexicographically less than vec1 in any solution. constraints;lexless Notes This constraint maintains GAC. constraints;lexless References See also
help constraints lexleq
for a similar constraint with non-strict lexicographic inequality. constraints;lexleq Description The constraint
lexleq(vec0, vec1)
takes two vectors vec0 and vec1 of the same length and ensures that vec0 is lexicographically less than or equal to vec1 in any solution. constraints;lexleq Notes This constraints achieves GAC. constraints;lexleq References See also
help constraints lexless
for a similar constraint with strict lexicographic inequality.
Definition at line 66 of file constraint_lex.h.
Member Function Documentation
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual triggerCollection LexLeqConstraint< VarArray1, VarArray2, Less >::setup_internal () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented from AbstractConstraint.
Definition at line 86 of file constraint_lex.h.
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual AbstractConstraint* LexLeqConstraint< VarArray1, VarArray2, Less >::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented from AbstractConstraint.
Definition at line 112 of file constraint_lex.h.
References AbstractConstraint::stateObj.
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual void LexLeqConstraint< VarArray1, VarArray2, Less >::propagate (int , DomainDelta) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 165 of file constraint_lex.h.
References AbstractConstraint::stateObj.
Referenced by LexLeqConstraint< VarArray1, VarArray2, Less >::full_propagate().
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual BOOL LexLeqConstraint< VarArray1, VarArray2, Less >::check_unsat (int , DomainDelta) [inline, virtual]
Checks incrementaly if constraint cannot be satisfied. Returns TRUE if constraint cannot be satisfied. This function should not be called unless check_unsat_full is called first. This is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 210 of file constraint_lex.h.
Referenced by LexLeqConstraint< VarArray1, VarArray2, Less >::full_check_unsat().
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual BOOL LexLeqConstraint< VarArray1, VarArray2, Less >::full_check_unsat () [inline, virtual]
Checks if a constraint cannot be satisfied, and sets up any data structures for future incremental checks. Returns TRUE if constraint cannot be satisfied. This function is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 249 of file constraint_lex.h.
References LexLeqConstraint< VarArray1, VarArray2, Less >::check_unsat().
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual void LexLeqConstraint< VarArray1, VarArray2, Less >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 268 of file constraint_lex.h.
References LexLeqConstraint< VarArray1, VarArray2, Less >::propagate(), and AbstractConstraint::stateObj.
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual BOOL LexLeqConstraint< VarArray1, VarArray2, Less >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 314 of file constraint_lex.h.
template<typename VarArray1, typename VarArray2, BOOL Less = false> virtual bool LexLeqConstraint< VarArray1, VarArray2, Less >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 332 of file constraint_lex.h.
The documentation for this struct was generated from the following file:
constraint_lex.h