Minion: BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed > Struct Template Reference
BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed > Struct Template Reference
#include <dynamic_sum.h>
Public Types
typedef
BoolLessSumConstraintDynamic
< VarArray, VarSum,
1-VarToCount > NegConstraintType
typedef VarArray::value_type VarRef
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
int & unwatched (int i)
BoolLessSumConstraintDynamic (StateObj *_stateObj, const VarArray &_var_array, VarSum _var_sum)
int dynamic_trigger_count ()
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
BOOL check_consistency ()
Checks the consistency of the constraint's data structures.
virtual void propagate (DynamicTrigger *dt)
Iterative propagation function.
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
template<bool b>
disable_if_c< b,
AbstractConstraint * >::type rev_implement ()
template<bool b>
enable_if_c< b,
AbstractConstraint * >::type rev_implement ()
Public Attributes
VarArray var_array
VarSum var_sum
MemOffset unwatched_indexes
int last
int num_unwatched
Detailed Description
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false>
struct BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >
constraints;watchsumgeq Description The constraint watchsumgeq(vec, c) ensures that sum(vec) >= c. constraints;watchsumgeq Notes For this constraint, small values of c are more efficient.
Equivalent to litsumgeq(vec, [1,...,1], c), but faster.
This constraint works on 0/1 variables only. constraints;watchsumgeq Reifiability This constraint is not reifiable. constraints;watchsumgeq References See also
help constraints watchsumleq help constraints litsumgeq constraints;watchsumleq Description The constraint watchsumleq(vec, c) ensures that sum(vec) <= c. constraints;watchsumleq Notes Equivalent to litsumgeq([vec1,...,vecn], [0,...,0], n-c) but faster.
This constraint works on binary variables only.
For this constraint, large values of c are more efficient. constraints;watchsumleq References See also
help constraints watchsumgeq help constraints litsumgeq
Definition at line 73 of file dynamic_sum.h.
Member Function Documentation
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> int BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::dynamic_trigger_count () [inline, virtual]
Defines the number of dynamic triggers the constraint wants. Must be implemented by any constraint.
Reimplemented from AbstractConstraint.
Definition at line 123 of file dynamic_sum.h.
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> virtual void BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 131 of file dynamic_sum.h.
References AbstractConstraint::dynamic_trigger_start(), AbstractConstraint::stateObj, and DynamicTrigger::trigger_info().
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> virtual void BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::propagate (DynamicTrigger *) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 220 of file dynamic_sum.h.
References BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::check_consistency(), AbstractConstraint::dynamic_trigger_start(), and DynamicTrigger::trigger_info().
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> virtual BOOL BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 277 of file dynamic_sum.h.
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> virtual bool BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 295 of file dynamic_sum.h.
template<typename VarArray, typename VarSum, int VarToCount = 1, BOOL is_reversed = false> virtual AbstractConstraint* BoolLessSumConstraintDynamic< VarArray, VarSum, VarToCount, is_reversed >::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented from AbstractConstraint.
Definition at line 317 of file dynamic_sum.h.
The documentation for this struct was generated from the following file:
dynamic_sum.h