Minion: LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed > Struct Template Reference
LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed > Struct Template Reference
V1 + ... Vn <= X.
#include <constraint_lightsum.h>
Public Member Functions
virtual string constraint_name ()
Method to get constraint name for debugging.
LightLessEqualSumConstraint (StateObj *_stateObj, const array< VarRef, size > &_var_array, const VarSum &_var_sum)
virtual triggerCollection setup_internal ()
Gets all the triggers a constraint wants to set up.
virtual bool get_satisfying_assignment (box< pair< int, DomainInt > > &assignment)
Looks for a valid partial assignment to a constraint.
virtual void propagate (int prop_val, DomainDelta)
Iterative propagation function.
virtual BOOL full_check_unsat ()
virtual BOOL check_unsat (int, DomainDelta)
virtual void full_propagate ()
Performs a full round of propagation and sets up any data needs by propagate().
virtual BOOL check_assignment (DomainInt *v, int v_size)
Checks if an assignment is satisfied.
virtual vector< AnyVarRef > get_vars ()
virtual AbstractConstraint * reverse_constraint ()
Returns the reverse of the current constraint.
template<bool b>
disable_if_c< b,
AbstractConstraint * >::type rev_implement ()
template<bool b>
enable_if_c< b,
AbstractConstraint * >::type rev_implement ()
Public Attributes
bool no_negatives
array< VarRef, size > var_array
VarSum var_sum
Detailed Description
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false>
struct LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >
V1 + ... Vn <= X.
Definition at line 28 of file constraint_lightsum.h.
Member Function Documentation
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual triggerCollection LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::setup_internal () [inline, virtual]
Gets all the triggers a constraint wants to set up.
This function shouldn't do any propagation. That is full_propagate's job.
Reimplemented from AbstractConstraint.
Definition at line 51 of file constraint_lightsum.h.
References array< _Tp, _Nm >::size().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual bool LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::get_satisfying_assignment (box< pair< int, DomainInt > > & assignment) [inline, virtual]
Looks for a valid partial assignment to a constraint.
The return value (in the box) is pairs of <varnum, domain value>, where varnum is in the same position as returned by get_vars.
Reimplemented from AbstractConstraint.
Definition at line 63 of file constraint_lightsum.h.
References array< _Tp, _Nm >::size().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual void LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::propagate (int , DomainDelta) [inline, virtual]
Iterative propagation function.
Can assume full_propagate is always called at least once before propagate
Reimplemented from AbstractConstraint.
Definition at line 96 of file constraint_lightsum.h.
Referenced by LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::full_propagate().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual BOOL LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::full_check_unsat () [inline, virtual]
Checks if a constraint cannot be satisfied, and sets up any data structures for future incremental checks. Returns TRUE if constraint cannot be satisfied. This function is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 111 of file constraint_lightsum.h.
References LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::check_unsat().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual BOOL LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::check_unsat (int , DomainDelta) [inline, virtual]
Checks incrementaly if constraint cannot be satisfied. Returns TRUE if constraint cannot be satisfied. This function should not be called unless check_unsat_full is called first. This is used by rarification
Reimplemented from AbstractConstraint.
Definition at line 114 of file constraint_lightsum.h.
Referenced by LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::full_check_unsat().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual void LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::full_propagate () [inline, virtual]
Performs a full round of propagation and sets up any data needs by propagate().
This function can be called during search if the function is reified
Implements AbstractConstraint.
Definition at line 122 of file constraint_lightsum.h.
References LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::propagate().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual BOOL LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::check_assignment (DomainInt * v, int v_size) [inline, virtual]
Checks if an assignment is satisfied.
This takes the variable order returned by, and is mainly only used by, get_table_constraint()
Implements AbstractConstraint.
Definition at line 128 of file constraint_lightsum.h.
References array< _Tp, _Nm >::size().
template<typename VarRef, std::size_t size, typename VarSum, BOOL is_reversed = false> virtual AbstractConstraint* LightLessEqualSumConstraint< VarRef, size, VarSum, is_reversed >::reverse_constraint () [inline, virtual]
Returns the reverse of the current constraint.
Used by rarification
Reimplemented from AbstractConstraint.
Definition at line 147 of file constraint_lightsum.h.
The documentation for this struct was generated from the following file:
constraint_lightsum.h