#ifndef CONSTRAINT_ENUM_H_BLARG
#define CONSTRAINT_ENUM_H_BLARG
enum ConstraintType {
CT_WATCHED_NEQ ,
CT_DISEQ ,
CT_DISEQ_REIFY ,
CT_EQ ,
CT_EQ_REIFY ,
CT_MINUSEQ ,
CT_MINUSEQ_REIFY ,
CT_WATCHED_LESS ,
CT_WATCHED_TABLE ,
CT_WATCHED_NEGATIVE_TABLE ,
CT_GADGET ,
CT_WATCHED_OR ,
CT_WATCHED_NEW_OR ,
CT_WATCHED_LIT ,
CT_WATCHED_NOTLIT ,
CT_REIFY ,
CT_CHECKEXPLN ,
};
#endif
